<a href="https://colab.research.google.com/github/HajiraRafiqa/Python-Practice/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ARRAYS

In [1]:
from array import *
vals = array('i', [8, 7, 6, 4, 3, 5])
print(vals)
print(vals.buffer_info())
print(vals.typecode)
print(vals.index(6))
vals.remove(4)
print(vals)
vals.reverse()
print(vals)
for i in range(len(vals)):
    print(vals[i], end=" ")
print("\n\n")
vals_1 = array('u', ['a', 'e', 'i', 'o', 'u'])
print(vals_1)
for i in vals_1:
    print(i, end=" ")
print("\n\n")

# When we don't know the type
arr = array(vals.typecode, (a*2 for a in vals))
for i in arr:
    print(i, end=" ")


# Write a Code to sort the array in ascending order

from array import *

nums = array('i', [8, 4, 7, 3, 5, 2])

for i in range(len(nums)):
    for j in range(len(nums)):
        if nums[i] < nums[j]:
            nums[i], nums[j] = nums[j], nums[i]

print(nums)

array('i', [8, 7, 6, 4, 3, 5])
(139697922712976, 6)
i
2
array('i', [8, 7, 6, 3, 5])
array('i', [5, 3, 6, 7, 8])
5 3 6 7 8 


array('u', 'aeiou')
a e i o u 


10 6 12 14 16 array('i', [2, 3, 4, 5, 7, 8])


#append()	Adds an element at the end of the list
#clear()	Removes all the elements from the list
#copy()	Returns a copy of the list
#count()	Returns the number of elements with the specified value
#extend()	Add the elements of a list (or any iterable), to the end of the current list
#index()	Returns the index of the first element with the specified value
#insert()	Adds an element at the specified position
#pop()	Removes the element at the specified position
#remove()	Removes the first item with the specified value
#reverse()	Reverses the order of the list
#sort()	Sorts the list
#Note: Python does not have built-in support for Arrays, but Python Lists can be used instead

In [2]:
from array import *

arr = array('i', [])
n = int(input("Enter the length of the Array : "))
for i in range(n):
    x = int(input("Enter the Next Value : "))
    arr.append(x)
print(arr)
val = int(input("Enter the Value for Search : "))
for i in range(1, len(arr)):
    if val == arr[i]:
        print("Value Found at Index : ", i)


# 1. Ceate an array With 5 Values and delete the value at index number 2 without using inbuilt funtion

arr1 = array('i', [7, 8, 4, 6, 9])
ind = int(input("Enter the index Number of The Number That You Want to Delete : "))
"""
c = [ e for i,e in enumerate(arr1) if i != ind ]
print(arr1)
print(c)
"""

arr1 = arr1[0:ind]+arr1[ind+1:]
print(arr1)

# 2. Write a code to reverse an array without using
#    in-built function

rev = arr1[::-1]
print(rev)

for i in range(int(len(arr1)/2)):
    n = arr1[i]
    arr1[i] = arr1[len(arr1)-i-1]
    arr1[len(arr1) - i - 1] = n

print(arr1)

Enter the length of the Array : 10
Enter the Next Value : 3
Enter the Next Value : 4
Enter the Next Value : 5
Enter the Next Value : 6
Enter the Next Value : 7
Enter the Next Value : 8
Enter the Next Value : 9
Enter the Next Value : 1
Enter the Next Value : 2
Enter the Next Value : 10
array('i', [3, 4, 5, 6, 7, 8, 9, 1, 2, 10])
Enter the Value for Search : 6
Value Found at Index :  3
Enter the index Number of The Number That You Want to Delete : 7
array('i', [7, 8, 4, 6, 9])
array('i', [9, 6, 4, 8, 7])
array('i', [9, 6, 4, 8, 7])


NumPY Arrays

In [3]:
from numpy import *

arr = array([[7, 8, 9, 5, 6, 4, 3], [3, 4, 5, 7, 6, 8, 9]])
print(arr)

[[7 8 9 5 6 4 3]
 [3 4 5 7 6 8 9]]


# 1. array() 
# 2. linspace()
# 3. logspace()
# 4. arange()
# 5. zeros()
# 6. ones()

In [4]:
from numpy import *

arr = array([1, 2, 3, 4, 5.3], int)
print(arr.dtype)
print(arr)

arr = linspace(0, 15, 20)
print(arr)

arr = arange(1, 15, 2)
print(arr)

arr = logspace(1, 40, 5)
print(arr)

arr = zeros(5, int)
print(arr)

arr = ones(5, int)
print(arr)

int64
[1 2 3 4 5]
[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]
[ 1  3  5  7  9 11 13]
[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
[0 0 0 0 0]
[1 1 1 1 1]


# Shallow Copy --> Both the arrays will be dependent on each other so if we update the value in one array it reflects in the other array too

# Deep Copy --> The Two Different arrays which are not linked in any way in which one array would be copied from other



In [5]:
from numpy import *
import itertools


arr1 = array([1, 2, 3, 4, 5])
arr2 = array([8, 9, 4, 2, 7])
arr3 = arr1 + arr2  # Vectorized Operation

print(sin(arr3))
print(cos(arr3))
print(tan(arr3))
print(min(arr3))
print(max(arr3))
print(sqrt(arr3))
print(sort(arr3))
print(sum(arr3))
print(concatenate([arr1, arr2]))


# Copying an array
print("\n\n")
arr4 = arr3    # Aliasing
print(arr3)
print(arr4)
print(id(arr3))
print(id(arr4))
print("\n\n")

arr4 = arr3.view()  # Shallow Copy

print(arr3)
print(arr4)
print(id(arr3))
print(id(arr4))
print("\n\n")

arr4 = arr3.copy()  # Deep Copy

print(arr3)
print(arr4)
print(id(arr3))
print(id(arr4))


# Assignment

for i in range(len(arr)):
    arr[i] = arr[i] + 5
print(arr)
arr = arr + 5
print(arr)


# 1. Write a code to add 2 arrays using forloop.

arr1 = array([2, 3, 4, 5, 6])
arr2 = array([8, 7, 6, 5, 4])
arr3 = array([0, 0, 0, 0, 0])
for i in range(len(arr1) | len(arr2)):
    arr3[i] = arr1[i]+arr2[i]
print(arr3)

# 2. Write a code to find the maximum value from an array without using in built functions

arr = array([82, 97, 26, 115, 44])
h = 0
for num in arr:
    if num > h:
        h = num
print("The Hihgest Number is : ", h)

[ 0.41211849 -0.99999021  0.6569866  -0.2794155  -0.53657292]
[-0.91113026  0.0044257   0.75390225  0.96017029  0.84385396]
[  -0.45231566 -225.95084645    0.87144798   -0.29100619   -0.63585993]
6
12
[3.         3.31662479 2.64575131 2.44948974 3.46410162]
[ 6  7  9 11 12]
45
[1 2 3 4 5 8 9 4 2 7]



[ 9 11  7  6 12]
[ 9 11  7  6 12]
139697852849872
139697852849872



[ 9 11  7  6 12]
[ 9 11  7  6 12]
139697852849872
139697852848144



[ 9 11  7  6 12]
[ 9 11  7  6 12]
139697852849872
139697852848912
[6 6 6 6 6]
[11 11 11 11 11]
[10 10 10 10 10]
The Hihgest Number is :  115
