<a href="https://colab.research.google.com/github/HajiraRafiqa/Python-Practice/blob/main/Python%20-%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
x =2.
x
_ + 10

12.0

lists - extend()- to add multiple values in lists.
        pop()- to pop out last element. uses index values.
        pop(1)- to remove 1 or specific value.
        remove(value)- to remove value from the list. uses elements.
        insert() 

In [9]:
from array import *

vals = array("f", [1.5,2.0,3,4,5])

print(vals)


array('f', [1.5, 2.0, 3.0, 4.0, 5.0])


Lamda function, filter(), map(), reduce()

In [1]:
nums = [1,2,3,4,5,6,7,8,9,10]

even = list(filter(lambda n : n % 2 == 0, nums))
print(even)

[2, 4, 6, 8, 10]


In [1]:
from numpy import *

arr = array([1,2,3,4,5])

print(arr)


[1 2 3 4 5]


In [8]:
from numpy import *

arr = array([
             [1,2,3],
             [4,5,6]
])

arr1 = arr.flatten()
arr2 = arr.reshape(2,3)
print(arr1)
print(arr2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


fibonacci series

In [2]:
def fib(n):

    a = 0
    b = 1

    if n == 1:
        print(a)

    else:
        print(a)
        print(b)

    for i in range(2,n):
        c = a + b
        a = b
        b = c
        print(a+b)

fib(10)

0
1
2
3
5
8
13
21
34
55
